#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 anmx
# For full license text, see https://opensource.org/licenses/MIT
#
# Description: Installs Astro using npm/npx.
#
# Note: this script runs at image-build time, before the user's workspace
# folder is mounted into the container. Project scaffolding therefore can't
# happen here -- it is deferred to a generated script invoked via the
# feature's "postCreateCommand", which runs after the workspace is mounted
# and in the context of the workspace folder (see
# https://containers.dev/implementors/features/#user-env-var).

set -e

VERSION="${VERSION:-latest}"
TEMPLATE="${TEMPLATE:-minimal}"
PROJECT="${PROJECT:-astro-project}"
INTEGRATIONS="${INTEGRATIONS//,/ }"
SKIPPROJECTCREATION="${SKIPPROJECTCREATION:-false}"
INSTALLGLOBALLY="${INSTALLGLOBALLY:-false}"

# Ensure Node.js is installed
if ! command -v npm &> /dev/null; then
    echo "ERROR: npm is not installed. Please install Node.js first."
    echo "Add the 'ghcr.io/devcontainers/features/node' feature before this one."
    exit 1
fi

if ! command -v npx &> /dev/null; then
    echo "ERROR: npx is not installed. Please install Node.js first."
    echo "Add the 'ghcr.io/devcontainers/features/node' feature before this one."
    exit 1
fi

# Normalize version string (remove 'astro@' prefix if present)
if [[ "$VERSION" == *@* ]]; then
    VERSION="${VERSION##*@}"
fi

echo "===================================="
echo "Installing Astro"
echo "===================================="
echo "Version: ${VERSION}"
echo "Template: ${TEMPLATE}"
echo "Project Name: ${PROJECT}"
echo "Skip Project Creation: ${SKIPPROJECTCREATION}"
echo "Install Globally: ${INSTALLGLOBALLY}"
if [[ -n "${INTEGRATIONS}" ]]; then
    echo "Integrations: ${INTEGRATIONS}"
fi
echo "===================================="

# Install Astro globally if requested
if [[ "${INSTALLGLOBALLY}" == "true" ]]; then
    echo "Installing Astro CLI globally..."
    npm install -g "astro@${VERSION}"
    INSTALLED_GLOBAL_VERSION="$(astro --version 2>/dev/null || true)"
    if [[ -z "${INSTALLED_GLOBAL_VERSION}" ]]; then
        echo "ERROR: Failed to verify global Astro CLI installation."
        exit 1
    fi
    echo "Astro CLI installed globally: ${INSTALLED_GLOBAL_VERSION}"
fi

# Project scaffolding can't happen at image-build time: the workspace folder
# isn't mounted yet, so anything created here would be baked into the image
# layer and shadowed by the real workspace mount at container run time.
# Instead, generate a script with the resolved options baked in, and run it
# via postCreateCommand (declared in devcontainer-feature.json), which
# executes after the workspace is mounted and from within it.
GENERATED_SCRIPT_DIR="/usr/local/share/devcontainer-features/astro"
GENERATED_SCRIPT="${GENERATED_SCRIPT_DIR}/create-project.sh"
mkdir -p "${GENERATED_SCRIPT_DIR}"

{
    printf '#!/usr/bin/env bash\n'
    printf '# Auto-generated by the astro devcontainer feature'\''s install.sh.\n'
    printf '# Do not edit by hand -- regenerated on every container rebuild.\n'
    printf 'set -euo pipefail\n\n'
    printf 'PROJECT=%q\n' "${PROJECT}"
    printf 'TEMPLATE=%q\n' "${TEMPLATE}"
    printf 'VERSION=%q\n' "${VERSION}"
    printf 'INTEGRATIONS=%q\n' "${INTEGRATIONS}"
    printf 'SKIP_PROJECT_CREATION=%q\n' "${SKIPPROJECTCREATION}"
    cat <<'SCRIPT_BODY'

if [[ "${SKIP_PROJECT_CREATION}" == "true" ]]; then
    exit 0
fi

if [[ -d "${PROJECT}" ]]; then
    echo "INFO: '${PROJECT}' already exists in the workspace. Skipping Astro project creation."
    exit 0
fi

CREATE_ARGS=("${PROJECT}" "--template" "${TEMPLATE}" "--yes" "--skip-houston")
if [[ -n "${INTEGRATIONS}" ]]; then
    read -ra INTEGRATION_ARRAY <<< "${INTEGRATIONS}"
    for integration in "${INTEGRATION_ARRAY[@]}"; do
        CREATE_ARGS+=("--add" "${integration}")
    done
fi

echo "Creating Astro project '${PROJECT}' (template: ${TEMPLATE}, astro version: ${VERSION})..."
npm create "astro@${VERSION}" -- "${CREATE_ARGS[@]}"

INSTALLED_VERSION="$(cd "${PROJECT}" && npx astro --version 2>/dev/null || true)"
if [[ -z "${INSTALLED_VERSION}" ]]; then
    echo "ERROR: Failed to verify Astro installation in '${PROJECT}'."
    exit 1
fi

echo "Successfully created Astro project '${PROJECT}' (astro ${INSTALLED_VERSION})."
SCRIPT_BODY
} > "${GENERATED_SCRIPT}"

chmod +x "${GENERATED_SCRIPT}"

echo "Done!"
