name: "Lint GitHub Actions workflows"
on:
    workflow_dispatch:
    pull_request:
        paths:
            - ".github/workflows/**"
    push:
        branches:
            - main
        paths:
            - ".github/workflows/**"

jobs:
    actionlint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7

            - name: "Check workflow files"
              run: |
                  echo "::add-matcher::.github/actionlint-matcher.json"
                  bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
                  ./actionlint -color
              shell: bash
